### PR TITLE
remove jsend

### PR DESCRIPTION
**Pull request by mvayngrib**
[cb-express-router](http://github.com/common-blockchain/cb-express-router) no longer supports it

btw, these latest few issues are from debugging the [common-blockchain service](https://github.com/tradle/bitcore-common-blockchain) for [bitcore-node](https://github.com/bitpay/bitcore-node) originally put together by @alexeykudinkin (i carved it out of https://github.com/tradle/bitcore-node/tree/common). It's not full-featured yet, but it's getting there

### CODE REVIEW

**Comment by dcousens** [comment]
@mvayngrib this is an interesting one,  since `cb-express-router`@master is clearly ahead of the game at ~`0.5.0` (see https://github.com/common-blockchain/common-blockchain/pull/26)

`0.2.x` uses `jsend`,  and that is what master of this repository is at.
@mvayngrib I'll add you to the organization such that you can make a branch and submit a PR for `0.5.0` for this repository.

We'll start moving that forward :+1:

**Comment by dcousens** [comment]
We should probably move all the commits in `cb-express-router` post `0.2.11` to a `0.5.0` branch too.

**Comment by mvayngrib** [comment]
@dcousens ah, didn't see that PR. Why 0.5.0 and not 1.0.0? Seems like there are lots of breaking changes, e.g. transactions.latest, blocks.latest

**Comment by dcousens** [comment]
@mvayngrib `1.0.0` could work too,  wasn't tied down to a particular version number.

**Pull request closed without merging**
